[server]
host = "127.0.0.1"
port = 3000

[database]
url = "sqlite:file:memdb1?mode=memory&cache=shared"
max_connections = 5
wal = true
wal_autocheckpoint = 1000

[writers.main]
batch_size = 100
flush_interval_ms = 500

[auth]
enabled = false
secret_path = "public.pem"
algorithm = "RS256"