[server]
host = "127.0.0.1"
port = 3000

[database]
url = "sqlite:cleopatra.db"
max_connections = 5
wal = true
wal_autocheckpoint = 1000

[writers.main]
batch_size = 100
flush_interval_ms = 500

[database_maintainence.main]
enabled = false
data_retention_days = 90
cron = "0 0 3 * * Sun"